### ISSUE TITLE
[FEATURE REQUEST] Save user registration to easily accessible table in S3

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gc-cloud-infrastructure#33]
To access the user registration information, we currently have to navigate to "geoschem_users" under dynamodbv2 in the AWS console (press explore, run scan, download using actions) or use the [aws cli](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/scan.html). It would greatly simplify things if the GCST could easily access the table by having the registrations trigger a dump into an table stored in S3. This would also facilitate sharing the information with the GCSC when requested.

**Comment by msulprizio** [comment]
Tagging @laestrada for input

**Comment by laestrada** [comment]
Hi Melissa, this can easily be done by modifying the lambda function that registers users using the boto3 dynamodb and s3 client. I am happy to handle this if you prefer

**Comment by lizziel** [comment]
Hi Lucas, if you have time to do this in the next few weeks that would be really helpful.
