### ISSUE TITLE
Feature request: Include GCPy as a submodule and use template benchmarking scripts directly from GCPy

### ISSUE THREAD

**Issue by yantosca** [geoschem/gc-cloud-infrastructure#47]
Currently, the cloud benchmarking relies on the following configuration files

- benchmarks/scripts/stages/resources/template.1hr_benchmark.yml
- benchmarks/scripts/stages/resources/template.1mo_benchmark.yml

However, it is easy to make changes to GCPy benchmarking YAML files and forget to make the corresponding changes in this repo.

It would be nice if we could migrate these template benchmarking scripts to the `GCPy/benchmark` folder.  This would require that GCPy be a submodule of gc-cloud-infrastructure. 

Tagging @laestrada @lizziel @msulprizio

**Comment by laestrada** [comment]
@yantosca no need for a submodule. The gc-cloud-infrastructure branch clones the dev branch of gcpy and can just use those files directly.
